### ISSUE TITLE
Dont show first(default) pic

### ISSUE THREAD

**Issue by ValeriaKochegarova** [ChristophAnastasiades/Lingallery#10]
Hi,
i use async request and when get images i can not get first (default) selected image , but when i click on 'thumbnails' then get on panel. How can i avoid this ? 
Thanks

**Comment by ChristophAnastasiades** [comment]
Hi, sorry I didn't understand. Can you explain again or maybe give an example?

**Comment by ValeriaKochegarova** [comment]
![Untitled](https://user-images.githubusercontent.com/32837526/62349217-ca016b80-b507-11e9-96a3-ee69d58c10a7.png)
By default chose image does not appear on main screen.  I get this images from api and when i click on image than on main screen appears image . I checked with mock data and it works good , but connect to api i have this problem. How can i avoid this ?
