### ISSUE TITLE
Error in console this.items[this.startImage] is undefined

### ISSUE THREAD

**Issue by erpriyanka** [ChristophAnastasiades/Lingallery#11]
I'm getting this error 
[Vue warn]: Error in mounted hook: "TypeError: this.items[this.startImage] is undefined"

**Comment by ChristophAnastasiades** [comment]
Did you pass the `items` prop the lingallery component? Please provide a code example.

**Comment by erpriyanka** [comment]
<lingallery :startImage="0" :addons="{ enableLargeView: true }" :iid.sync="currentId" :width="width" :height="height" :accentColor="accentColor" :items="items"/> 

<script>
    export default {
       props: {  }, 
        data(){
            return {
               startImage : 0,
                items : [],
                currentId: null,
                accentColor : '#ed691f',
             }
        },
          methods: {
              ProductImages()
             {
               axios.get(`/api/productimages/${this.$route.params.id}`)
               .then(response => {
               this.items = response.data;
           })
            .catch(error => {
                console.error(error);
            })    
            },
           }
      }
</script>

**Comment by JeromeDesseaux** [comment]
hi, 

If you set your items 'on the fly' using, for example, props, you should map your props array using the beforeMounted method. Anyway vue will mount your component and Lingallery will try to access the first object of the items array but those items actually dont exist (yet). Using this method will ensure that those objects are created BEFORE mounting the component. 

For instance : 
`beforeMount: function() {
    let images = this.images;
    let endpoint = this.endpoint;
    this.items = images.map(function(image) {
      return {
        src: endpoint + "/images/" + image.image,
        thumbnail: endpoint + "/thumbnails/" + image.image
      };
    });
  },`
