### ISSUE TITLE
Gallery with only one image displays infinite spinner

### ISSUE THREAD

**Issue by JeromeDesseaux** [ChristophAnastasiades/Lingallery#12]
Hi! 

First : thanks for this awesome work! 

I use your library in a Laravel project and I'm facing a problem. I have objects that can have one or more images. Using your library with many images is working fine but I got a problem with a single image. 

When the images array only got on image, it displays fine, I can use large image preview ... but I still have the "next" and "previous" icon and clicking on it led me to an infinite spinner. 

Maybe could you disable for "next" and "previous" fields when the array contains a single image ? 

My workaround (simple but working) : Setting rightControlClass & leftControlClass to hidden using a computed property 

```javascript
<lingallery
    :iid.sync="currentId"
    :addons="{ enableLargeView: true }"
    :responsive="true"
    :rightControlClass="hideControls"
    :leftControlClass="hideControls"
    :items="items"
  />
```

```javascript
hideControls: function() {
      return this.items.length === 1 ? "hidden" : "";
    }
```

Thanks again!

**Comment by ChristophAnastasiades** [comment]
@JeromeDesseaux thank you for your comment. This should be fixed in the latest release dc1b080
. The large image click will be disabled and the left / right controls are hidden when only a single image is passed to Lingallery.
