### ISSUE TITLE
Images are always 600x400

### ISSUE THREAD

**Issue by nezaboravi** [ChristophAnastasiades/Lingallery#14]
Thanks for this gallery.
Unfortunately i cant get any image to fit a full space of the div where component is loaded.
Looks like it always maintain 600x400 defaults even i remove them from component.
Here is how it looks like:
```
<template>
    <lingallery :iid.sync="currentId" :items="items"/>
</template>
<script>
    import Lingallery from 'lingallery';

    export default {
        props: ['images', 'thumbs'],
        data() {
            return {
                responsive: true,
                items: [
                    {
                        src: 'https://lorempixel.com/900/500/',
                        thumbnail: 'https://picsum.photos/64/64',
                        caption: 'Some Caption',
                        id: 'someid1',
                    },
                    {
                        src: 'https://picsum.photos/600/400/?image=10',
                        thumbnail: 'https://picsum.photos/64/64/?image=10',
                    }],
                currentId: null,
            }
        },
        components: {
            Lingallery,
        },
    };
</script>
```

As you can see i set it to be responsive and i tried many different sizes both from picsum and lorempixel, however it always shows 600x400 in dev inspector.
That makes is kind of useless for me. 
Is there a way around it or i migh b missing something from docs?

<img width="1222" alt="Screenshot 2019-11-26 12 38 49" src="https://user-images.githubusercontent.com/1515172/69602326-b98e7700-1049-11ea-9362-e6bc63fe0aa1.png">

EDIT:
Removing style from <figure> tag directly in dev console,  makes image size full. 
<img width="938" alt="Screenshot 2019-11-26 12 41 02" src="https://user-images.githubusercontent.com/1515172/69602416-1853f080-104a-11ea-8d30-a5673156d175.png">

**Comment by nezaboravi** [comment]
@ChristophAnastasiades any thoughts on this?

**Comment by ChristophAnastasiades** [comment]
@nezaboravi if you want the images to be very wide you could add a very high width like 3000 pixels. Then the image would scale up to 3000 pixels while still being responsive meaning it will not exceed the surrounding container. Could you try that?
