### ISSUE TITLE
[Vue warn]: Failed to resolve directive: touch

### ISSUE THREAD

**Issue by alexeydg** [ChristophAnastasiades/Lingallery#3]
[Vue warn]: Failed to resolve directive: touch

(found in <Lingallery> at Lingallery.vue) vue.common.js:612

    warn44VueJS

run lingallery.umd.js:1066 notify lingallery.umd.js:1083 flush lingallery.umd.js:1662

**Comment by alexeydg** [comment]
fix:
import Lingallery from 'lingallery';
Vue.component('lingallery', Lingallery);

import Vue2TouchEvents from 'vue2-touch-events'
Vue.use(Vue2TouchEvents)

**Comment by ChristophAnastasiades** [comment]
Thank you, I fixed this issue in the latest commit.
