### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by HaNdTriX** [ChristophAnastasiades/Lingallery#35]
## Issue

This module is using [hammerjs](https://hammerjs.github.io/) without releasing bound DOM Elements:

## In detail

Check out the following code:

https://github.com/ChristophAnastasiades/Lingallery/blob/dc1b080753af3354757822e444567cc0fdfdcbb9/src/components/Lingallery.vue#L119-L124

Here we are creating a new Hammer instance. This instance:

- stores a DOM-Reference to an image element
- binds to some events

Nevertheless when Vue unmounts the component the references still persist, preventing them from being garbage collected.

## Solution

1. Keep a reference to the instance
2. Destroy it when it is no longer needed

    ```js
    hammerjs.destroy()
    ```

## Untested solution

```js
...
  directives: {
    swipe: {
      bind: function (el, binding) {
        if (typeof binding.value === 'function') {
          binding.hammer = new Hammer(el)
          binding.hammer.get('swipe').set({ direction: Hammer.DIRECTION_HORIZONTAL, threshold: 5 })
          binding.hammer.on('swipe', binding.value)
        }
      },
      unbind: function(el, binding) {
        if (binding.hammer) {
          binding.hammer.destroy()
        }
      }
    }
  },
...
```

## Docs

- https://hammerjs.github.io/api/#destroy
- https://vuejs.org/v2/cookbook/avoiding-memory-leaks.html
- https://012.vuejs.org/guide/custom-directive.html

**Comment by ChristophAnastasiades** [comment]
Fixed by latest commit (version 1.3.4).
