### ISSUE TITLE
dont work styles

### ISSUE THREAD

**Issue by alexeydg** [ChristophAnastasiades/Lingallery#4]
![2019-03-13_14-15-11](https://user-images.githubusercontent.com/2332107/54275020-a2325b00-459a-11e9-946f-3892b0b84982.png)

**Comment by AustineA** [comment]
yeah I'm experiencing the same error on nuxt

**Comment by AustineA** [comment]
I think i found a fix for the style issue. 

Paste this inside your component's <style> </style>

`.lingallery {
        max-width: 100%;
    }
    figure {
        position: relative;
        margin: 0;
        padding: 0;
        max-width: 100%;
        text-align: center;
        cursor: pointer;
    }
    figure img {
        max-width: 100%;
        max-height: 100%;
        transition: opacity .25s ease;
    }
    figure img.loading {
        opacity: 0.25;
        min-height: 200px;
        transition: opcacity .25s ease;
    }
    figure a.control {
        position: absolute;
        top: 0;
        padding-left: 5px;
        padding-right: 15px;
        height: 100%;
        display: none;
        font-size: 20px;
        color: #fff;
        cursor: pointer;
        text-shadow: 0 0 20px rgba(0, 0, 0, 0.75);
    }
    figure a.control:before {
        position: relative;
        top: calc(50% - 12px);
    }
    figure a.control.left {
        left: 0;
    }
    figure a.control.right {
        right: 0;
    }
    figure:hover a.control {
        display: block;
    }
    .lingallery_caption {
        position: absolute;
        bottom: 0;
        left: 0;
        padding: 4px 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.75);
        font-size: 1em;
    }
    .lingallery_thumbnails {
        overflow-x: auto;
        width: 100%;
    }
    .lingallery_thumbnails_content {
        margin-top: 2px;
        width: auto;
        white-space: nowrap;
    }
    .lingallery_thumbnails .lingallery_thumbnails_content_elem {
        display: inline-block;
    }
    .lingallery_thumbnails .lingallery_thumbnails_content_elem img {
        border: 2px solid #fff;
        cursor: pointer;
    }
    .lingallery_spinner {
        position: absolute;
        left: 50%;
        top: calc(50% - 32px);
    }
    .lingallery_spinner > div {
        z-index: 9999;
        position: relative;
        left: -50%;
    }
    /*
     * Scrollbar styling
     */
    .lingallery_thumbnails::-webkit-scrollbar {
        height: 6px;
    }
    .lingallery_thumbnails::-webkit-scrollbar-track {
        border-radius: 10px;
        background: #eaeaea;
    }
    .lingallery_thumbnails::-webkit-scrollbar-thumb {
        border-radius: 10px;
        background: #b4b4b4;
    }
    .lingallery_thumbnails::-webkit-scrollbar-thumb:window-inactive {
        background: rgba(100,100,100,0.4);
    }`

**Comment by alexeydg** [comment]
yes, I decided so
