### ISSUE TITLE
Get errors when adding accentColor

### ISSUE THREAD

**Issue by Tchilly** [ChristophAnastasiades/Lingallery#6]
Get erros when tying to add accentColor or baseColor to the mix.
```
<lingallery :width="800" :height="400" :responsive=true :accentColor="#ffffff" :mobile-height="300" :items="[
    {src: 'https://picsum.photos/800/500/?image=0', thumbnail: 'https://picsum.photos/64/64/?image=0'},
    {src: 'https://picsum.photos/800/500/?image=10', thumbnail: 'https://picsum.photos/64/64/?image=10'}
]"/>
```

**Error;**
app.js:47084 [Vue warn]: Error compiling template:
invalid expression: Unexpected identifier in
    #ffffff
 Raw expression: :accentcolor="#ffffff"

**Comment by ChristophAnastasiades** [comment]
@Tchilly please try to pass the accentColor as a string by either adding single quotation marks or by removing the double colon. So either `:accentColor="'#ffffff'"` or `accentColor="#ffffff"`.

**Comment by Tchilly** [comment]
Figured it out, needed to be passed as; 
`accent-color="#ffffff"`
Without the ':'.. All sorted
