### ISSUE TITLE
Is it possible select current id in gallery ? 

### ISSUE THREAD

**Issue by ValeriaKochegarova** [ChristophAnastasiades/Lingallery#9]
Hi, 
I am using lingallery package and need to get current id in chosen image .  I get ids from api and f.e when user chose image i need to get current id 
How can i get it ? 
Thanks

**Comment by ChristophAnastasiades** [comment]
Hi, I just added a new version which now accepts IDs. You can simply pass any ID to an image like this:

`<lingallery @current-id="handleIdChange" :width="600" :height="400" :items="[
    {id:'someid1', src: 'https://picsum.photos/600/400/?image=0', thumbnail: 'https://picsum.photos/64/64/?image=0', alt: 'Some alt text', caption: 'Some Caption'}
]"/>`

"someid1" will be the ID of the first image. The @current-id handler will always update the currently selected image and you can access it in a method like handleIdChange. I updated the Readme so you can see a full example.

**Comment by ValeriaKochegarova** [comment]
Thanks, but its not working

**Comment by ChristophAnastasiades** [comment]
Sorry, I forgot I used the new sync syntax. Instead of the @current-id handler please try using `:iid.sync="currentId"`. I updated the Readme for an example.

**Comment by vkobzar** [comment]
> Sorry, I forgot I used the new `sync` syntax. Instead of the `@current-id` handler please try using `:iid.sync="currentId"`. I updated the Readme for an example.

Hey @ChristophAnastasiades! Looks like it doesn't work for now https://github.com/ChristophAnastasiades/Lingallery/commit/acd9a6b4044709ec1cf3fd19b46e6e34d6e4d166#diff-406c13e06200c10ac752201a15507043R339
BTW Is it possible to add some classes for active thumb item?
